version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql-db-volume:/var/lib/mysql
    networks:
      - airflow-net
    restart: always

  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    networks:
      - airflow-net
    restart: always

  airflow-webserver:
    image: apache/airflow:2.7.0
    container_name: airflow-webserver
    depends_on:
      - postgres
      - mysql
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./scripts:/opt/airflow/scripts
    ports:
      - "8080:8080"
    networks:
      - airflow-net
    command: webserver
    restart: always

  airflow-scheduler:
    image: apache/airflow:2.7.0
    container_name: airflow-scheduler
    depends_on:
      - postgres
      - mysql
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./scripts:/opt/airflow/scripts
    networks:
      - airflow-net
    command: scheduler
    restart: always

volumes:
  postgres-db-volume:
  mysql-db-volume:

networks:
  airflow-net:
